global:
  scrape_interval: 10s
  scrape_timeout: 5s
  
  external_labels:
    deployment_name: $DEPLOYMENT_NAME

remote_write:
  - url: http://victoria-metrics:8428/api/v1/write
  - url: https://xxxxxx.grafana.net/api/prom/push
    basic_auth:
      username: 1220892
      #password_file: /etc/prometheus/grafana.env
      password: xxxxxxxxxxxxxxx

scrape_configs:

  - job_name: 'orthanc'
    scrape_interval: 10s
    metrics_path: /tools/metrics-prometheus
    static_configs:
      - targets: ['orthanc:8042']
    basic_auth:
      username: orthanc
      password_file: /etc/prometheus/orthanc.env

  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['prometheus:9090']

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  
  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']
    
  # - job_name: 'postgres_exporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']