global:
  scrape_interval: 10s
  scrape_timeout: 5s
  
  external_labels:
    deployment_name: $DEPLOYMENT_NAME

remote_write:
  - url: $REMOTE_WRITE_URL
    basic_auth:
      username: $REMOTE_WRITE_USERNAME
      password: $REMOTE_WRITE_PASSWORD

scrape_configs:

  - job_name: 'orthanc'
    scrape_interval: 10s
    metrics_path: /tools/metrics-prometheus
    static_configs:
      - targets: ['$ORTHANC_SERVICE_NAME:$ORTHANC_SERVICE_PORT']
    basic_auth:
      username: $ORTHANC_USERNAME
      password: $ORTHANC_PASSWORD
