global:
  scrape_interval: 6s
  scrape_timeout: 5s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'orthanc'
    scrape_interval: 10s
    metrics_path: /tools/metrics-prometheus
    static_configs:
      - targets: ['orthanc:8042']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']