FROM grafana/grafana:8.2.6

COPY datasource.yml /etc/grafana/provisioning/datasources

COPY dashboard.json /etc/grafana/provisioning/dashboards
COPY dashboard.yml /etc/grafana/provisioning/dashboards

